### ISSUE TITLE
onResponse returns json even though the header might not be json

### ISSUE THREAD

**Issue by edgesoft** [cerebral/cerebral-module-http#27]
We need to look at the actual response to make sure it's not just text. If we make a request to an api endpoint that does not exists it returns a String and will be Uncaught SyntaxError when parsed as json.

**Comment by christianalfoni** [comment]
I believe I fixed that?

``` js
    var result = xhr.responseText

    if (xhr.getResponseHeader('content-type').indexOf('application/json') >= 0) {
      result = JSON.parse(xhr.responseText)
    }
```

:)
