### ISSUE TITLE
httpGet should support query parameters.

### ISSUE THREAD

**Issue by kgdev** [cerebral/cerebral-module-http#3]
Something like 

``` js
httpGet('/search', {
  start:{start},
  count:10
})
```

or `httpGet(url, {...query parameters are here})`

**Comment by Guria** [comment]
There is no single standard how to stringify query params. But we can bundle qs one and provide a way to define own serializers.

**Comment by Guria** [comment]
Now you can try just use concatenation:

``` js
httpGet(['/search?start=', 'input:/start', '&count=', 'input:/count'])
```

**Comment by christianalfoni** [comment]
Yeah, and the factories are for simple use cases:

``` js
httpGet(`/search?start=${start}&count=10`)
```

If you need to use more logic, like grabbing the start from the state etc. you build a custom action. Or can do like @Guria suggets, though I think it reads better when you just create an action there.
