### ISSUE TITLE
Passing default options doesn't work

### ISSUE THREAD

**Issue by henri-hulski** [cerebral/cerebral-module-http#4]
I'm using the example from README.md:

``` javascript
controller.addModules({

  // Can pass any default options which
  // will be used on all requests
  http: Http({
    baseUrl: '/api'
  })
})
```

But when I have an action like

``` js
function getTodos({services, output}) {
  services.http.get('todos')
    .then(output.success)
    .catch(output.error);
}

getTodos.async = true;

export default getTodos;
```

the base URL doesn't apply and I get the error

```
GET http://localhost:5000/todos 404 (Not Found)
```

Using `services.http.get('/api/todos')` does work.

**Comment by christianalfoni** [comment]
Hi there! 

Sorry about this, baseUrl is actually not implemented. I have a tendency to write docs first, to point out how I want it to work :) But forgot to implement this. Let me remove from README for now. Feel free to implement it if you want to

**Comment by fvgoto** [comment]
It works for me if that option is written the official axios way: `baseURL` -- with "URL" in all uppercase letters.
[See axios](https://github.com/mzabriskie/axios/blame/master/README.md#L194).
(My comment on the README-updating [commit](https://github.com/cerebral/cerebral-module-http/commit/ffc2e63c15084d8d6cf0aaf219763cec6bd44da3) seems too hidden...)

I guess this issue may thus be closed.

**Comment by christianalfoni** [comment]
Ah, great, thanks for that input @fvgoto !
